version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWD
    ports:
      - ${MARIADB_PORT:-3306}:3306

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWD
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    env_file:
      - .env
